# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    groups:
      "Git SubModules":
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "ci(deps-dev)"
    groups:
      "GitHub Actions":
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: chore(deps-dev)
    groups:
      "NPM":
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/GroupBox.Avalonia.Sample/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: build(sample)
    groups:
      "GroupBox.Avalonia.Sample":
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/GroupBox.Avalonia/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      include: scope
      prefix: fix
      prefix-development: build
    groups:
      "GroupBox.Avalonia":
        patterns:
          - "*"
