name: Build

on:
  workflow_call:

jobs:
  build:
    name: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Pack Solution
      run: dotnet pack