on:
  workflow_call:

env:
  DOTNET_ROLL_FORWARD: "Major"

jobs:
  build:
    name: Build (${{matrix.os}})
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: NPM - Clean Install
        run: npm ci
      - name: NPM - Audit Signatures
        run: npm audit signatures

      - name: Pack Solution
        run: dotnet pack
