on:
  workflow_call:

env:
  DOTNET_ROLL_FORWARD: "Major"

jobs:
  build:
    name: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Pack Solution
        run: dotnet pack