# inspired by https://github.com/GitTools/GitVersion/blob/main/.github/workflows/_unit_tests.yml
on:
  workflow_call:

jobs:
  unit_test:
    name: ${{ matrix.os }} - ${{ matrix.targetFramework }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        targetFramework: [ 'net8.0', 'net7.0', 'net6.0' ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci

      - uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.x'

      - run: dotnet test --framework=${{ matrix.targetFramework }} 